Repository Wanted-Internship-Team-Careerly/SNS-Integration-Feed-Service, pull requests merged in 2023-11, with the labels that each got.

#16 [feature] 통계 API
  src/main/java/com/snsIntegrationFeedService/common/error/CustomErrorCode.java
  src/main/java/com/snsIntegrationFeedService/hashtag/entity/Hashtag.java
  src/main/java/com/snsIntegrationFeedService/hashtag/repository/HashtagRepository.java
  src/main/java/com/snsIntegrationFeedService/hashtag/service/HashtagService.java
  src/main/java/com/snsIntegrationFeedService/post/CountType.java
  src/main/java/com/snsIntegrationFeedService/post/DateType.java
  src/main/java/com/snsIntegrationFeedService/post/controller/StaticsController.java
  src/main/java/com/snsIntegrationFeedService/post/dto/request/CreatePostRequestDto.java
  src/main/java/com/snsIntegrationFeedService/post/dto/request/StaticsRequestDto.java
  src/main/java/com/snsIntegrationFeedService/post/dto/response/StaticsResponseDto.java
  src/main/java/com/snsIntegrationFeedService/post/entity/Post.java
  src/main/java/com/snsIntegrationFeedService/post/repository/PostRepositoryCustom.java
  src/main/java/com/snsIntegrationFeedService/post/repository/PostRepositoryImpl.java
  src/main/java/com/snsIntegrationFeedService/post/service/PostService.java
  src/main/java/com/snsIntegrationFeedService/post/service/StaticService.java
  src/main/java/com/snsIntegrationFeedService/postHashtag/entity/PostHashtag.java
  src/main/java/com/snsIntegrationFeedService/postHashtag/repository/PostHashtagRepository.java
  src/main/java/com/snsIntegrationFeedService/postHashtag/service/PostHashtagService.java
  src/main/java/com/snsIntegrationFeedService/user/entity/User.java
  src/test/java/com/snsIntegrationFeedService/post/service/PostServiceTest.java
Labels: feature

#22 [feature] 가입승인 API
  src/main/java/com/snsIntegrationFeedService/certificateCode/controller/CertificateCodeController.java
  src/main/java/com/snsIntegrationFeedService/certificateCode/dto/CertificateCodeRequestDto.java
  src/main/java/com/snsIntegrationFeedService/certificateCode/entity/CertificateCode.java
  src/main/java/com/snsIntegrationFeedService/certificateCode/repository/CertificateCodeRepository.java
  src/main/java/com/snsIntegrationFeedService/certificateCode/service/CertificateCodeService.java
  src/main/java/com/snsIntegrationFeedService/common/error/CustomErrorCode.java
  src/main/java/com/snsIntegrationFeedService/common/security/WebSecurityConfig.java
  src/main/java/com/snsIntegrationFeedService/user/entity/User.java
  src/main/java/com/snsIntegrationFeedService/user/service/UserService.java
Labels: feature

#19 [docs] readme 작성
  README.md
  src/main/java/com/snsIntegrationFeedService/hashtag/entity/Hashtag.java
  src/main/java/com/snsIntegrationFeedService/post/service/PostService.java
  src/main/java/com/snsIntegrationFeedService/postHashtag/entity/PostHashtag.java
Labels: documentation

#24 [test] 유저 서비스 레이어 테스트
  src/test/java/com/snsIntegrationFeedService/user/service/UserServiceTest.java
Labels: test
